// <auto-generated />
using DemoServerAppForHMAC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoServerAppForHMAC.Migrations
{
    [DbContext(typeof(ServerAppDbContext))]
    partial class ServerAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoServerAppForHMAC.Models.ClientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ClientSecretKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ClientSecretSalt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ClientInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "WebApp",
                            ClientName = "XYZ Company",
                            ClientSecretKey = "XYZCompany123",
                            ClientSecretSalt = "Test"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "MobileApp",
                            ClientName = "ABC Company",
                            ClientSecretKey = "XYZCompany123",
                            ClientSecretSalt = "Test"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "DeskTop",
                            ClientName = "123 Company",
                            ClientSecretKey = "XYZCompany123",
                            ClientSecretSalt = "Test"
                        });
                });

            modelBuilder.Entity("DemoServerAppForHMAC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Salary = 10000m,
                            UserRole = "Software Engineer",
                            Username = "Rama"
                        },
                        new
                        {
                            Id = 2,
                            Salary = 500000m,
                            UserRole = "Manager",
                            Username = "Krishna"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
