// <auto-generated />
using System;
using AutoMapperUsageInWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoMapperUsageInWebAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250317184751_IntialMigration")]
    partial class IntialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoMapperUsageInWebAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SupplierPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "DELL",
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dell Laptop",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 1000m,
                            SerialNumber = "ELE-DELL-Laptop-2025-001",
                            StockQuantity = 100,
                            SupplierName = "MainITSupplier",
                            SupplierPrice = 900m,
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "OnePlus",
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OnePlus SmartPhone",
                            IsActive = true,
                            Name = "Mobile",
                            Price = 500m,
                            SerialNumber = "ELE-OnePlus-Mobile-2025-01",
                            StockQuantity = 100,
                            SupplierName = "MainITSupplier",
                            SupplierPrice = 300m,
                            UpdatedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
